leftnav:
- identifier: 0904c6ba-af62-4a9b-8956-18fe27521ce1
  name: "Teaching La Princesse de Cl\xE8ves Website"
  pageRef: "/external-resources/teaching-la-princesse-de-cl\xE8ves-website_0904c6ba-af62-4a9b-8956-18fe27521ce1"
  weight: 10
